{{- if and (gt (int .Values.replicaCount) 1) .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "etcd-ui.fullname" . }}
  labels: {{- include "etcd-ui.labels" . | nindent 4 }}
spec:
  {{- with .Values.pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "etcd-ui.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
